In [3]:
%pip install torch torchvision torchaudio --upgrade

   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------------ --------------------- 0.8/1.7 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 4.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.5 MB 4.2 MB/s eta 0:00:01
   --------------------- ------------------ 1.3/2.5 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 3.8 MB/s eta 0:00:00

  Attempting uninstall: torchvision

    Found existing installation: torchvision 0.21.0

   ---------------------------------------- 0/2 [torchvision]
    Uninstalling torchvision-0.21.0:
   ---------------------------------------- 0/2 [torchvision]
      Successfully uninstalled torchvision-0.21.0
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvi

In [1]:
import torch
print(torch.__version__)

2.7.0+cpu


In [3]:
if torch.cuda.is_available():
    print("gpu is available")
    print(f"using gpu: {torch.cuda.get_device_name(0)}")
else:
    print("gpu not available, using cpu. ")

gpu not available, using cpu. 


## Creating a Tensor

In [10]:
# using empty
a = torch.empty(2,3)
"""
    it creates a space in mempry and it shows whatever values were in that space
"""

# type check
type(a)

torch.Tensor

In [11]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3) # gives random values each time

tensor([[0.8502, 0.7708, 0.3942],
        [0.7099, 0.1612, 0.8208]])

In [16]:
# use of seed
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)
# above cell gives same tensor values as seed was same

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [19]:
# using tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
# other methods

# arange
print("using arange -> ", torch.arange(0,10,2))

# using linspace
print("using linspace -> ", torch.linspace(0,10,10))

# using eye
print("using eye -> ", torch.eye(5))

# using full
print("using full", torch.full((3,3), 5))

using arange ->  tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [21]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
x.shape

torch.Size([2, 3])

In [32]:
# creating another tensor of same shape as above
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [33]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

## Tensor data types

In [34]:
x.dtype

torch.int64

In [35]:
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [36]:
torch.tensor([1,2,4], dtype = torch.float64)

tensor([1., 2., 4.], dtype=torch.float64)

In [39]:
# using to()
x.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [40]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Mathematical Operations

### 1. Scaler Operation

In [44]:
X = torch.rand(2,3)

In [47]:
X + 2
X - 2
X * 3
X / 3
(X * 100) // 3 # integer division
((X*100)//3)% 2 # mod
X**2


tensor([[0.9938, 0.5723, 0.0501],
        [0.0914, 0.0318, 0.6787]])

### 2. Element wise operation


In [49]:
a = torch.rand(2,3)
b = torch.rand_like(a)

print(a)
print(b)

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])
tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])


In [ ]:
a + b
a-b
a * b
a ** b
a % b


tensor([[0.0087, 0.0079, 0.6175],
        [0.2423, 0.0518, 0.4683]])

In [54]:
d = torch.tensor([1.9,2.3,2.7,4.4])

In [55]:
# round
torch.round(d)

tensor([2., 2., 3., 4.])

In [56]:
# ceil
torch.ceil(d)

tensor([2., 3., 3., 5.])

In [57]:
# floor
torch.floor(d)

tensor([1., 2., 2., 4.])

In [58]:
# clamp
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 2.7000, 3.0000])

### 3. Reduction Operation


In [65]:
e = torch.randint(size = (2,3), low = 0 , high = 10, dtype = torch.float32)
e

tensor([[2., 6., 7.],
        [7., 8., 3.]])

In [63]:
# sum
torch.sum(e)
#sum along columns
torch.sum(e, dim = 0)
# sum along the rows
torch.sum(e , dim = 1)



tensor([22, 25])

In [69]:
# mean 
torch.mean(e)
# sum along columns
torch.mean(e, dim = 0)
# sum along rows
# torch.sum(e, dim = 1)

tensor([4.5000, 7.0000, 5.0000])

In [70]:
# max and  min 
torch.max(e)
torch.min(e)

tensor(2.)

In [72]:
# argmax
torch.argmax(e) # tells position of maximum valed number 
# argmin
torch.argmin(e) # tells position of minimum valed number 

tensor(0)

In [74]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9454, 0.7116, 0.1157],
        [0.6574, 0.3451, 0.0453]])
tensor([[0.9798, 0.5548, 0.6868],
        [0.4920, 0.0748, 0.9605]])


In [ ]:
m.add_(n) # _ means inplace operation

tensor([[1.9251, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

In [76]:
m

tensor([[1.9251, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

In [77]:
n

tensor([[0.9798, 0.5548, 0.6868],
        [0.4920, 0.0748, 0.9605]])

In [79]:
b = m 
b

tensor([[1.9251, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

In [80]:
# if we make
m[0][0] = 0

In [81]:
# then 
m

tensor([[0.0000, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

In [83]:
# b also changes
b

# there is not a new tensor , but a pointer pointing to tensor m

tensor([[0.0000, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

In [86]:
b  = m.clone()

In [88]:
m

tensor([[0.0000, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

In [89]:
b

tensor([[0.0000, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

In [90]:
m[0][0] = 1

In [91]:
m

tensor([[1.0000, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

In [92]:
b

tensor([[0.0000, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

## Reshape Operations

In [100]:
b = torch.randn(2,3,4)
b

tensor([[[ 0.8680,  0.7109,  0.9353,  0.7676],
         [-0.2889,  0.6672,  0.1637, -0.5416],
         [-0.8724,  0.1006,  0.5509,  0.1763]],

        [[ 0.0863,  0.5136,  0.1915,  0.9862],
         [-1.5533,  0.8499,  0.4945,  0.4633],
         [ 1.1470,  0.8598,  0.3610, -1.4282]]])

In [101]:
# permute
b.permute(2,0,1)

# piche wala aage aa gya, aage wala beech me and beech wala piche

tensor([[[ 0.8680, -0.2889, -0.8724],
         [ 0.0863, -1.5533,  1.1470]],

        [[ 0.7109,  0.6672,  0.1006],
         [ 0.5136,  0.8499,  0.8598]],

        [[ 0.9353,  0.1637,  0.5509],
         [ 0.1915,  0.4945,  0.3610]],

        [[ 0.7676, -0.5416,  0.1763],
         [ 0.9862,  0.4633, -1.4282]]])

In [102]:
# unsqueeze
# image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape


torch.Size([1, 226, 226, 3])

In [103]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and Pytorch

In [104]:
import numpy as np

In [105]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [106]:
b = a.numpy()
b

array([1, 2, 3], dtype=int64)

In [107]:
type(b)

numpy.ndarray

In [108]:
c = np.array([1,2,4])
c

array([1, 2, 4])

In [109]:
torch.from_numpy(c)

tensor([1, 2, 4], dtype=torch.int32)