In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## train_test_split

In [6]:
X_train,X_test, y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

### scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [36]:
X_train

array([[-0.35823882, -0.28968111, -0.3595848 , ..., -0.54148132,
        -0.2054433 , -0.26947818],
       [-0.47188059,  1.10191032, -0.32755846, ...,  1.58915944,
         2.28611744,  6.63045654],
       [ 0.03950737, -0.2505138 , -0.02987772, ..., -0.60100818,
        -0.42995067, -0.39960475],
       ...,
       [-0.53154252, -0.30350487, -0.56159712, ..., -0.49864002,
         0.31893054, -0.15440757],
       [ 1.71572348,  0.09277614,  1.60757168, ...,  0.40914463,
         0.22787161, -1.33683872],
       [-0.15936572, -1.23430443, -0.13786397, ..., -0.36650842,
         0.24357143, -0.13021048]])

In [9]:
y_train

79     B
9      M
298    B
534    B
271    B
      ..
323    M
37     B
155    B
321    M
221    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding


In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,

### Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [27]:
class MySimpleNN():
    def __init__(self,X):
        
        self.weights = torch.rand(X.shape[1], 1,  dtype= torch.float64, requires_grad= True)
        self.bias = torch.zeros(1,  dtype= torch.float64, requires_grad= True)
        
    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # clamp prediction to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon,1-epsilon)
        
        # calculate loss
        loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
        return loss
        
    
    

### Important parameters


In [16]:
learning_rate = 0.1
epochs = 25

### Training Pipeline


In [34]:
model = MySimpleNN(X_train_tensor)

# define loop
for i in range(epochs):
    # foreward pass
    y_pred = model.forward(X_train_tensor)
    
    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)
    
    # backward pass
    loss.backward()
    
    # parameters update1
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
        
    # zero gradient
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    # print loss in each epoch
    print(f"Epoch : {i + 1} , Loss : {loss.item()}")
    
    

Epoch : 1 , Loss : 2.92664627190912
Epoch : 2 , Loss : 2.7751233508403703
Epoch : 3 , Loss : 2.6197402665795737
Epoch : 4 , Loss : 2.459118164880194
Epoch : 5 , Loss : 2.2958101409671903
Epoch : 6 , Loss : 2.1351983568832624
Epoch : 7 , Loss : 1.9739796329651922
Epoch : 8 , Loss : 1.815257616289436
Epoch : 9 , Loss : 1.6602125449704195
Epoch : 10 , Loss : 1.5126744543272428
Epoch : 11 , Loss : 1.3741398103104963
Epoch : 12 , Loss : 1.2473038312412126
Epoch : 13 , Loss : 1.137866142558936
Epoch : 14 , Loss : 1.0470263094250805
Epoch : 15 , Loss : 0.9747943578298011
Epoch : 16 , Loss : 0.9197158879831833
Epoch : 17 , Loss : 0.879080541434233
Epoch : 18 , Loss : 0.8495720599253483
Epoch : 19 , Loss : 0.8280019275583941
Epoch : 20 , Loss : 0.8117856421467143
Epoch : 21 , Loss : 0.7990788884581063
Epoch : 22 , Loss : 0.7886798676626133
Epoch : 23 , Loss : 0.7798469435748931
Epoch : 24 , Loss : 0.7721315713762312
Epoch : 25 , Loss : 0.7652599597675015


In [29]:
model.weights

tensor([[ 0.1082],
        [-0.1470],
        [-0.0246],
        [-0.2367],
        [ 0.0717],
        [ 0.1616],
        [-0.2642],
        [-0.3430],
        [-0.3659],
        [-0.1154],
        [-0.0955],
        [ 0.1047],
        [ 0.4935],
        [ 0.3766],
        [ 0.6138],
        [-0.0256],
        [ 0.1411],
        [-0.5015],
        [ 0.0985],
        [ 0.3014],
        [ 0.0243],
        [ 0.1155],
        [ 0.1565],
        [-0.1243],
        [ 0.1523],
        [ 0.2219],
        [ 0.0732],
        [ 0.2316],
        [ 0.3984],
        [-0.3520]], dtype=torch.float64, requires_grad=True)

In [30]:
model.bias

tensor([-0.6093], dtype=torch.float64, requires_grad=True)

### Evaluation

In [33]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy : {accuracy.item()}")    

    

Accuracy : 0.5701754093170166
